language: php
php:
  - '5.4'
  - '5.6'
  - '7.0'
  - hhvm # on Trusty only
  - nightly
git: 
    depth: 3

 script:
    -yarn build

    deploy:
        provider: pages
        skip-cleanuo: true
        keep-history: true
        github-token: $GITHUB_TOKEN
        target-branch: gh-page
        commit_massage: "deploy del proyecto"

        on:
            branch: master